sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary':
            estimated_delivery_time:
                template: 'shop/estimated_delivery_time.html.twig'
                priority: 250
        
        'sylius_shop.base.header.navbar.menu':
            mangaddict_link:
                template: 'mangaddict/header/menu/mangaddict_link.html.twig'
                priority: 600
