sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary':
            estimated_delivery_time:
                template: 'shop/estimated_delivery_time.html.twig'
                priority: 250
        
        'sylius_shop.base.header.navbar.menu':
            mangaddict_link:
                template: 'mangaddict/header/menu/mangaddict_link.html.twig'
                priority: 600

    #     sylius_twig_hooks:
    # hooks:
    #     'sylius_shop.product.show.content.info.summary':
    #         header:
    #             template: '@SyliusShop/product/show/content/info/summary/header.html.twig'
    #             priority: 500
    #         average_rating:
    #             template: '@SyliusShop/product/show/content/info/summary/average_rating.html.twig'
    #             priority: 400
    #         prices:
    #             template: '@SyliusShop/product/show/content/info/summary/prices.html.twig'
